rpgWorld: "world"
locations:
  abandonedMines:
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
regions:
  0:
    name: "&aHub"
    x: 0
    z: 0
    x2: 100
    z2: 100
npcs:
mySQL:
  host: localhost
  username: root
  password: ''
  port: 3306
  database: database